### ISSUE TITLE
Some kind of motivation for this?

### ISSUE THREAD

**Issue by kozross** [leptonyu/tensors#1]
Reading the Haddocks, it's very difficult for me to understand why I'd want this or for what. A worked example, or some kind of motivation, would be really helpful.

**Comment by leptonyu** [comment]
My motivation is quite simple, I want create a library to calculate tensors, like `numpy.ndarray` in python. I also use `shape` to describe the shape of tensor the same as in `numpy`.

I had two options:
1. Put `shape` in data and check at runtime to make sure operations accept tensor the right `shape`.
2. Put `shape` on type, and check at compile time to make sure that.

Haskell has the ability to deal with both, but the second option will make things much more clear and clean. For example:

```Haskell

-- Bad Example
newtype Tensor n = Tensor ([Int], [Int] -> n)

instance Num (Tensor n) where
  (Tensor (sa,ta))  +  (Tensor (sb,tb)) =
      if match sa sb 
           then Tensor (sa,\i -> ta i + tb i)
           else error "shape not match"
  ...
```
In the above example, we put `shape` in data. So it is not natural to implement `Num` instance, because different `shape` of tensors, they can't add together. This comes the idea that different `shape` of tensors may have different types, then it becomes quite natural to put `shape` on the type.

Type level programming makes runtime coding quite easy and simple, without any `shape` checking. 


This library is still working in progress and not so fast. Examples in Haddocks are the worked examples.

Does this answer your question?

Thanks
